// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQADBt7dnAzycBPU1E5T830d-oodgRmFE',
    appId: '1:150787047550:web:2f104580444a0fa26ad82f',
    messagingSenderId: '150787047550',
    projectId: 'authexample1-e4ffa',
    authDomain: 'authexample1-e4ffa.firebaseapp.com',
    storageBucket: 'authexample1-e4ffa.firebasestorage.app',
    measurementId: 'G-0R40NGNP09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmGsE5GfbqReFa8iEIviwa1tZi6jvhjf4',
    appId: '1:150787047550:android:fe285a6d83ed5fa86ad82f',
    messagingSenderId: '150787047550',
    projectId: 'authexample1-e4ffa',
    storageBucket: 'authexample1-e4ffa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGLI19ouyv2s8u4MdBg7YYiKJoBtpEVeo',
    appId: '1:150787047550:ios:e1c1ba839dac237b6ad82f',
    messagingSenderId: '150787047550',
    projectId: 'authexample1-e4ffa',
    storageBucket: 'authexample1-e4ffa.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGLI19ouyv2s8u4MdBg7YYiKJoBtpEVeo',
    appId: '1:150787047550:ios:e1c1ba839dac237b6ad82f',
    messagingSenderId: '150787047550',
    projectId: 'authexample1-e4ffa',
    storageBucket: 'authexample1-e4ffa.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQADBt7dnAzycBPU1E5T830d-oodgRmFE',
    appId: '1:150787047550:web:a56a77d1a90c06b66ad82f',
    messagingSenderId: '150787047550',
    projectId: 'authexample1-e4ffa',
    authDomain: 'authexample1-e4ffa.firebaseapp.com',
    storageBucket: 'authexample1-e4ffa.firebasestorage.app',
    measurementId: 'G-MXF4Y1QGWV',
  );
}
